### ISSUE TITLE
Possible to not redirect away from the customer account section?

### ISSUE THREAD

**Issue by JayBox325** [instantcommerce/shopify-headless-theme#10]
I'm building a Next.js Shopify site and I'm using this to redirect users that visit the Shopify domain to the Next.js site. But we're still looking to lean on an out-the-box template for users to log in and see their orders. Is this possible with this theme?

**Comment by leeuwis** [comment]
Hey @JayBox325, this can be done relatively easy by adding some logic to (to not redirect):
https://github.com/instantcommerce/shopify-headless-theme/blob/master/theme/layout/theme.liquid#L154

Hopefully this helps!
