### ISSUE TITLE
Variable storefrontBaseUrl is undefined + URL match check is wrong

### ISSUE THREAD

**Issue by abencun-symphony** [instantcommerce/shopify-headless-theme#14]
In `theme.liquid` the variable `storefrontBaseUrl` is referred to wrongly. Looking at the changes made in commit [f43aae1](https://github.com/instantcommerce/shopify-headless-theme/commit/f43aae1f6490271bd5c36769aca702cecbdd9c96) it looks like `storefrontBaseUrl` was renamed to `storefrontHostname` but not in all places it should've been renamed.

Furthermore at line 43 `redirectUrl.startsWith(storefrontBaseUrl + fromPath)` isn't working as expected due to the fact that the `redirectUrl` that is initialized as `var redirectUrl = window.location.href.replace(currentHostname, storefrontHostname);` can never start with the provided value as it will always start with `http://` or `https://`.

Can't open the PR with the fixes at the moment so just quickly reporting on the issue.

**Comment by leeuwis** [comment]
Hey @abencun-symphony, good catch, something lines indeed didn't get properly updated in that commit. I've opened #18 which should fix this specific issue.
