### ISSUE TITLE
cannot create a custom redirect for root/index

### ISSUE THREAD

**Issue by EricWVGG** [instantcommerce/shopify-headless-theme#15]
The location of our online store is `https://ourdomain.com/swag`. The following custom redirect doesn't appear to work:

```
/ > /swag
```

Otherwise working well. Thank you for writing this tool.

**Comment by leeuwis** [comment]
Seems like some logic in the custom redirects was incorrect, should be fixed by #18

**Comment by EricWVGG** [comment]
Just installed, works great. Thank you!!
