### ISSUE TITLE
[question] login page redirection fixed?

### ISSUE THREAD

**Issue by y-nk** [instantcommerce/shopify-headless-theme#20]
### problem

Not sure if i did it right, but I had a bug in the login process. 

After redirecting the customer to the checkout page, when they clicked "log in", they'd be redirected to the `{{ settings.storefront_hostname }}/password` for some reason.

I couldn't track easily why I was redirected to `/password` so I deactivated Javascript in advance and navigated to the `Login` link where i could see that there was a redirection block at the end of the page (see details ↓)

<details>
  <summary>Login page with redirect block</summary>
  <img width="533" alt="image" src="https://github.com/instantcommerce/shopify-headless-theme/assets/411625/adce9285-feb1-4079-9d27-fe937eed2dd1">
</details>

I tracked it down to the main `layouts/template.liquid` here:

https://github.com/instantcommerce/shopify-headless-theme/blob/4a8a8f124aea576269a6c8d631b5119574fe6e6b/layout/theme.liquid#L220-L239

...and `should_redirect` was (hopefully) explained in a comment a bit above:

https://github.com/instantcommerce/shopify-headless-theme/blob/4a8a8f124aea576269a6c8d631b5119574fe6e6b/layout/theme.liquid#L149-L154

So according to the logic of the comment, the redirection **should not happen when we navigate to the login page**.

In order to debug I just added this:

```liquid
<!-- should_redirect={{ should_redirect }} ⇒
```

And to my surprise the value wasn't a boolean but rather the `template` value.

<img width="341" alt="image" src="https://github.com/instantcommerce/shopify-headless-theme/assets/411625/395e6b08-677b-4679-a577-b8ae21fca2bc">

### solution

I changed this:

https://github.com/instantcommerce/shopify-headless-theme/blob/4a8a8f124aea576269a6c8d631b5119574fe6e6b/layout/theme.liquid#L154

To become that:

```
{%- assign should_redirect = false -%}
{% if template != 'customers/login' or settings.multipass_login %}
  {% assign should_redirect = true %}
{% endif %}
```

and it seems now that `should_redirect` is a boolean which is `true/false` according to the logic of the comment.

### question(s)

- was this a bug?
- how come nobody had the issue?
- do you need a PR?

**Comment by leeuwis** [comment]
Hey @y-nk, you should probably remove password protection from your theme so Shopify doesn't redirect all pages to the `/password` page. For more info see: https://help.shopify.com/en/manual/online-store/themes/password-page#remove-password-protection-from-your-online-store

Let me know if that fixed the issue for you.

**Comment by fnvon** [comment]
Hi @leeuwis,

we do experience the same issue. Our store is public and has no password-protection. Everytime i click on "login" on the checkoutpage, i get redirected to my custom storefront. That's not what I want, nor what I expected, as I want the user to be redirected to login on the shopify side. multipass is also disable in the settings.

I used the fix from @y-nk and changed line 154 in the `theme.liquid` file. that fixed the issue.

thanks for providing this custom theme. let me know, if you need any further information.
