### ISSUE TITLE
/favicon.ico returns 404 in checkout

### ISSUE THREAD

**Issue by garrettboatman** [instantcommerce/shopify-headless-theme#25]
Is there a way to get a favicon working in checkout? I have a favicon uploaded to `Theme Settings > Favicon`, but doesn't appear to be working:

<img width="132" alt="Screenshot 2023-10-29 at 1 41 52 AM" src="https://github.com/instantcommerce/shopify-headless-theme/assets/3833961/d75f9cbb-3389-435d-a5fc-7d7ed7d1b629">

**Comment by leeuwis** [comment]
Hey @garrettboatman, the `shopify-headless-theme` does not include a `checkout.liquid` file, so this is outside the scope of the repo. Maybe this can guide you in the right direction: https://community.shopify.com/c/shopify-design/how-do-we-add-a-favicon-to-our-checkout-page/m-p/1339332
