### ISSUE TITLE
Edit checkout code

### ISSUE THREAD

**Issue by rondo10** [instantcommerce/shopify-headless-theme#26]
How can I edit checkout code?
There is no reference for the checkout page in the source code and I don't find any default checkout code on shopify

**Comment by jannisstefanis** [comment]
AFAIK You can only edit the checkout page with Shopify Plus

**Comment by leeuwis** [comment]
That is correct, if you are on Shopify Plus, you can request access to the `checkout.liquid` file to edit the checkout.
