### ISSUE TITLE
/password > / (not working)

### ISSUE THREAD

**Issue by ollebergkvist** [instantcommerce/shopify-headless-theme#7]
I've password-protected the default Shopify store.
Custom front end lives on: godsent.gg
The checkout lives on a custom subdomain: checkout.godsent.gg

When I try to set up a custom redirect to link to the index page of godsent.gg:
/password > /

I'm greeted by the Redirecting template after clicking on the logotype on the checkout page, the "Click here" link wants to ref to:
checkout.godsent.gg/undefined but it should go to godsent.gg/

How do I solve this?

**Comment by ollebergkvist** [comment]
Solved it by modifying the source code in theme.liquid

**Comment by ollebergkvist** [comment]
@leeuwis Of course!

For this specific project, the user dashboard is not implemented.

So all that was needed is to redirect the customer to the index route of the custom storefront, in case the customer clicks the logo on the order confirmation page.

This means I could hardcode the desired URL on line 174 and 175 in theme.liquid.

**Comment by blanklob** [comment]
Can you share the snippet please, if you dont mind.
