### ISSUE TITLE
Theme seems to be broken

### ISSUE THREAD

**Issue by ollebergkvist** [instantcommerce/shopify-headless-theme#8]
Did this break for someone else?

We just started seeing an issue, when users click on the checkout button they are redirected to my-domain.myshopify.com/password instead of the checkout page.

**Comment by leeuwis** [comment]
Hey @ollebergkvist, is it possible that [Password protection](https://help.shopify.com/en/manual/online-store/themes/password-page) is enabled in your Shopify store?

**Comment by ollebergkvist** [comment]
Did Shopify change something?

We had the storefront password protected for 2 months, and now it appears that Shopify is password protecting the checkout as well. I guess that's the issue here.

**Comment by leeuwis** [comment]
I'm not 100% sure but I think it already also protected the checkout, but if you are logged into their admin environment in Shopify you might not notice it since it will not show the password protection in that case.
